### ISSUE TITLE
How to use (docs)?

### ISSUE THREAD

**Issue by yuomtheara** [msavin/JetSetter#1]
How to use (docs)?

**Comment by msavin** [comment]
You just run meteor add msavin:jetsetter

**Comment by yuomtheara** [comment]
I know about install, but don't know how to use?
Ex: `Session.set(.....)`

**Comment by msavin** [comment]
Just press control and m 😄

**Comment by yuomtheara** [comment]
Thanks, like `Mongol' package.

**Comment by yuomtheara** [comment]
can use out of `Session` like can any meteor method?

**Comment by msavin** [comment]
huh?
