### ISSUE TITLE
Colorize exception

### ISSUE THREAD

**Issue by tcastelli** [msavin/JetSetter#10]
Hello, from time to time i get this exception when using jetsetter

"Exception in template helper: JetSetter.colorize@http://localhost:3000/packages/msavin_jetsetter.js?f8d14aa94bfc32be0adb9c71f84852ea79b412b1:165:7
.content@http://localhost:3000/packages/msavin_jetsetter.js?f8d14aa94bfc32be0adb9c71f84852ea79b412b1:427:10
bindDataContext/<@http://localhost:3000/packages/blaze.js?4e49999979a58da0e2265f7bd3f5910f9901b07b:2786:14
Blaze._wrapCatchingExceptions/<@http://localhost:3000/packages/blaze.js?4e49999979a58da0e2265f7bd3f5910f9901b07b:1607:14
wrapHelper/</<@http://localhost:3000/packages/blaze.js?4e49999979a58da0e2265f7bd3f5910f9901b07b:2834:14
Template._withTemplateInstanceFunc@http://localhost:3000/packages/blaze.js?4e49999979a58da0e2265f7bd3f5910f9901b07b:3382:12
wrapHelper/<@http://localhost:3000/packages/blaze.js?4e49999979a58da0e2265f7bd3f5910f9901b07b:2833:1
Spacebars.call@http://localhost:3000/packages/spacebars.js?7bafbe05ec09b6bbb6a3b276537e4995ab298a2f:172:12
Spacebars.mustacheImpl@http://localhost:3000/packages/spacebars.js?7bafbe05ec09b6"[…] meteor.js:888:10

**Comment by msavin** [comment]
Hmm can you please try the latest version and see if it persists? List of packages would be helpful too

**Comment by tcastelli** [comment]
i couldn't recreate the exception, we can close it for now I think

**Comment by msavin** [comment]
Thanks for letting me know. Maybe there was a new update that resolved the issue.
