### ISSUE TITLE
Failed to decode font LiberationMono-Bold

### ISSUE THREAD

**Issue by ghost** [msavin/JetSetter#13]
Getting the following warning:

Failed to decode downloaded font: http://localhost:3000/packages/meteortoys_toykit/public/LiberationMono-Bold.ttf

msavin:jetsetter 1.0.19

**Comment by ghost** [comment]
meteortoys:toykit 0.8.2

**Comment by rhkina** [comment]
Me too, but with msavin:mongol...

**Comment by msavin** [comment]
Fixed - please update and let me know if the issue still persists.
