### ISSUE TITLE
JetSetter package broken after 1.2.0.2 update

### ISSUE THREAD

**Issue by garyfoo** [msavin/JetSetter#14]
Hello, I have just discovered that the JetSetter package breaks after updating Meteor to specifically 1.2.02. I have attached my console error log just incase you need more details. To mimic this issue, you could try creating a todos example project and add the jetsetter package using Meteor 1.2.0.2
<img width="1279" alt="screen shot 2015-09-30 at 2 17 13 pm" src="https://cloud.githubusercontent.com/assets/5109700/10184315/591e571e-677e-11e5-81c5-8808736b604b.png">

**Comment by Hamatek** [comment]
the same for me +1:+1:

**Comment by boustanihani** [comment]
Getting this too:

```
TypeError: Property 'undefined' of object [object Object] is not a function
    at Package (packages/meteortoys_toykit/packages/meteortoys_toykit.js:290:1)
```

**Comment by guidouil** [comment]
it's actually on two lines and 1.2.0.1 did not have this issue... go figure

``````
W20151002-10:33:48.116(2)? (STDERR) /Users/gui/.meteor/packages/meteor-tool/.1.1.9.nz6cu0++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20151002-10:33:48.116(2)? (STDERR)                         throw(ex);
W20151002-10:33:48.116(2)? (STDERR)                               ^
W20151002-10:33:48.121(2)? (STDERR) TypeError: Property 'undefined' of object [object Object] is not a function
W20151002-10:33:48.121(2)? (STDERR)     at Package (packages/meteortoys_toykit/packages/meteortoys_toykit.js:290:1)
W20151002-10:33:48.121(2)? (STDERR)     at Package (packages/meteortoys_toykit/packages/meteortoys_toykit.js:293:1)```
``````

**Comment by guidouil** [comment]
Yes un-installed mongol and jetsetter, then re-installed and everything is fine. Thanks, stay awesome :)

**Comment by garyfoo** [comment]
Works fine after following what @guidouil said. Cheers
