### ISSUE TITLE
'setSubscriptionKeys' is undefined

### ISSUE THREAD

**Issue by dbhandel** [msavin/JetSetter#2]
Mongol is awesome and I've updated it. JetSetter looks great but awn I add it I get the following error:
Uncaught TypeError: Cannot read property 'setSubscriptionKeys' of undefined.

I haven't updated Meteor to 1.0.4 because I'm waiting for some packages I depend on to be updated. Would 1.0.3 explain the error?
Thanks

**Comment by msavin** [comment]
Sounds strange - can you tell me which versions of the packages you are using? Maybe they're not updating because of an older Meteor version.. which shouldn't cause a problem.

**Comment by dbhandel** [comment]
I didn't notice that when I add JetSetter, Mongol gets rolled back from 1.0.6 to 0.5.4. See all meteor list printout after adding JetSetter:

accounts-password              1.0.6\* Password support for accounts
accounts-ui                    1.1.4\* Simple templates to add login widgets to an app
aldeed:autoform                4.2.2\* Easily create forms with automatic insert and update, and automatic reactive validation.
aldeed:collection2             2.3.2  Automatic validation of insert and update operations on the client and server.
iron:router                    1.0.7  Routing specifically designed for Meteor
meteor-platform                1.2.1\* Include a standard set of Meteor packages in your app
meteorhacks:search-source      1.2.0  Reactive Data Source for Search
mike:mocha                     0.5.2  Run mocha tests in the browser
msavin:jetsetter               1.0.0  Visual Get/Set Tool for Sessions
msavin:mongol                  0.5.4\* The insanely handy development package for Meteor.
smeevil:syntax-error-notifier  1.0.4\* Display a warning modal if your app crashes due to a syntax error, auto reloads on fix
twbs:bootstrap                 3.3.2\* Bootstrap (official): the most popular HTML/CSS/JS framework for responsive, mobile first projects
useraccounts:bootstrap         1.8.1  Accounts Templates styled for Twitter Bootstrap.

**Comment by msavin** [comment]
Strange going to test. Thanks for letting me know.

**Comment by msavin** [comment]
I cloned the todos app then installed both packages and it works fine. Do you have a hunch of what else it may be? It's tough for me to say without seeing your code.

**Comment by dbhandel** [comment]
I don't but I'll look into it further and get back. Thanks for checking.
