### ISSUE TITLE
Feature request: show subscriptions from other DDP connections than the default

### ISSUE THREAD

**Issue by remcoder** [msavin/JetSetter#5]
Currently, only the subscriptions are shown that are are made over the default DDP connection with `Meteor.subscribe`. I'd like to see the status of subscriptions made over a secondary DDP connection, made as follows:

```
var conn = DDP.connect('http://localhost:3002');

conn.subscribe('some_pub', function() {
})
```

**Comment by msavin** [comment]
yup coming
