### ISSUE TITLE
Fonts become unreadable when editing value

### ISSUE THREAD

**Issue by nilnullzip** [msavin/JetSetter#7]
Just installed today. Really cool stuff! I can read the values easily. But when I click edit, the font becomes the same color as the background, so unreadable.

**Comment by msavin** [comment]
Thanks for the tip - going to look into a patch. Are you using any CSS framework  along with it?

**Comment by nilnullzip** [comment]
Running Less Bootstrap package: nemo64:bootstrap. Stock configuration with no changes.

**Comment by msavin** [comment]
The new update should fix it

**Comment by msavin** [comment]
@nilnullzip can you please confirm if this helped?

**Comment by nilnullzip** [comment]
Yes the fonts are now readable. However, they lose their syntax sensitive coloring when variable opened for editing. (Not a big deal.)

**Comment by msavin** [comment]
Ah yes that's by design. Thanks for reporting.
