### ISSUE TITLE
Cannot create new Session

### ISSUE THREAD

**Issue by nilnullzip** [msavin/JetSetter#8]
When on the set new session tab, there is no area that will accept a value. Presumably the area under the name box should be editable, but not so.

**Comment by msavin** [comment]
Are you sure? The area underneath is "content editable." May I ask what browser/config you're running?

**Comment by nilnullzip** [comment]
Seems to work on Safari, and is broken on Chrome. OSX Macbook Retina. I'm running the latest of everything. Actually appears related to the size of the window. If window is half screen width, then it is not editable. If the window is full screen, then the edit box allows some editing, but the editable part is on the right side of the edit box. Very odd.

**Comment by msavin** [comment]
Can you send a screen shot of the window? There must be an element overlapping it.

**Comment by nilnullzip** [comment]
Here you go Max. The highlighted part is what will accept text. I've got the inspector on it.

![screen shot 2015-03-29 at 2 37 26 pm](https://cloud.githubusercontent.com/assets/872634/6887893/e9a55498-d621-11e4-88d4-b5f02f88bbe2.png)

**Comment by msavin** [comment]
Strange issue - I wonder if you have some sort of property on the div selector in CSS. 
Can you try adding "width: 100%" to the "JetSetter_editor" class?

**Comment by msavin** [comment]
Closing since I had not heard back
